package JFrames;
import java.sql.Connection;
import funciones.funcionesBBDD;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.Blob;
/**
 *
 * @author Carmen
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public Busqueda() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Conectar base de datos
        Connection conec= funcionesBBDD.conectar();
        //Recoger el datos de la consulta
        PrincipalJFrame consulta = new PrincipalJFrame();

        // Primera Consulta
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        radioSerie = new javax.swing.JRadioButton();
        radioPeli = new javax.swing.JRadioButton();
        bBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mPortada = new javax.swing.JMenu();
        mContenido = new javax.swing.JMenu();
        mSeries = new javax.swing.JMenuItem();
        mPeliculas = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mAcerca = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenu();
        mPerfil = new javax.swing.JMenuItem();
        mLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        buttonGroup1.add(radioSerie);
        radioSerie.setText("Series");

        buttonGroup1.add(radioPeli);
        radioPeli.setText("Películas");

        bBuscar.setText("Buscar");

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addComponent(radioSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPeli)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        mPortada.setText("Portada");
        mPortada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPortadaMouseClicked(evt);
            }
        });
        mPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPortadaActionPerformed(evt);
            }
        });
        jMenuBar1.add(mPortada);

        mContenido.setText("Contenido");

        mSeries.setText("Series");
        mContenido.add(mSeries);

        mPeliculas.setText("Peliculas");
        mContenido.add(mPeliculas);

        jMenuBar1.add(mContenido);

        mAyuda.setText("Ayuda");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/cerrar1.png"))); // NOI18N
        mSalir.setText("Salir de la aplicación");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mAyuda.add(mSalir);

        mAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/ayuda1.png"))); // NOI18N
        mAcerca.setText("Acerca de...");
        mAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaActionPerformed(evt);
            }
        });
        mAyuda.add(mAcerca);

        jMenuBar1.add(mAyuda);

        mUsuario.setText("Usuario");

        mPerfil.setText("Perfil");
        mPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPerfilActionPerformed(evt);
            }
        });
        mUsuario.add(mPerfil);

        mLogout.setText("Log Out");
        mUsuario.add(mLogout);

        jMenuBar1.add(mUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Evento que al pulsar Salga de la aplicación
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        //Salir de la aplicación
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPerfilActionPerformed
        // TODO add your handling code here:
        //Mostrar el FRAME del PERFIL del USUARIO
        PerfilJFrame perfil = new PerfilJFrame();
        //Mostrar el frame de perfil
        perfil.setVisible(true);
        //ocultar este frame
        this.setVisible(false);
    }//GEN-LAST:event_mPerfilActionPerformed

    private void mAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaActionPerformed
        // TODO add your handling code here:
        AcercaDe acerca = new AcercaDe(this,rootPaneCheckingEnabled);
        acerca.setVisible(true);
        
    }//GEN-LAST:event_mAcercaActionPerformed

    private void mPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPortadaActionPerformed
       
    }//GEN-LAST:event_mPortadaActionPerformed

    private void mPortadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPortadaMouseClicked
         //Pasarnos a la Ventana portada
        PrincipalJFrame portada = new PrincipalJFrame();
        portada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mPortadaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mAcerca;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mContenido;
    private javax.swing.JMenuItem mLogout;
    private javax.swing.JMenuItem mPeliculas;
    private javax.swing.JMenuItem mPerfil;
    private javax.swing.JMenu mPortada;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mSeries;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JRadioButton radioPeli;
    private javax.swing.JRadioButton radioSerie;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
