/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import Funciones.funcionesBBDD;

/**
 *
 * @author imba
 */
public class CambioContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambioContraseña
     */
    public CambioContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aceptarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        nuevaContrasena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptarBoton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        aceptarBoton.setText("Aceptar");
        aceptarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aceptarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aceptarBotonMouseExited(evt);
            }
        });
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 93, -1));

        cancelarBoton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cancelarBoton.setText("Cancelar");
        cancelarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarBotonMouseExited(evt);
            }
        });
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 93, -1));

        nuevaContrasena.setForeground(new java.awt.Color(204, 204, 204));
        nuevaContrasena.setText("Introduce la nueva contraseña");
        nuevaContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaContrasenaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevaContrasenaMouseExited(evt);
            }
        });
        nuevaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, -1));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Cambiar Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarBotonMouseEntered

    private void aceptarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarBotonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarBotonMouseExited

    private void cancelarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBotonMouseEntered

    private void cancelarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBotonMouseExited

    }//GEN-LAST:event_cancelarBotonMouseExited

    private void nuevaContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaContrasenaMouseClicked


    }//GEN-LAST:event_nuevaContrasenaMouseClicked

    private void nuevaContrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaContrasenaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaContrasenaMouseExited

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void nuevaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaContrasenaActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        funcionesBBDD.loadDriver();
        funcionesBBDD.connect();
        funcionesBBDD.isConnected();
        funcionesBBDD.cambioContrasena(funcionesBBDD.user, nuevaContrasena.getText());
    }//GEN-LAST:event_aceptarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
