/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import Contenido.Contenido;
import javax.swing.ImageIcon;
import JFrames.PortadaJFrame;
import com.mysql.cj.Query;
import funciones.funcionesBBDD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
/**
 *
 * @author Carmen
 */
public class MostrarContenido extends javax.swing.JFrame {
    Object[] datos= new Object[5];
    PortadaJFrame contenido = new PortadaJFrame();
    /**
     * Creates new form MostrarContenido
     */
    public MostrarContenido(){
        initComponents();
        this.setTitle("Mostrar Contenido");
        this.setLocationRelativeTo(null);
        imgContenido.setIcon(new ImageIcon(contenido.imagen1));
        String sqlMostrarContenido ="Select Nombre, Descripcion,Director,Duracion from contenido where Imagen='"+ contenido.imagen1+ "'";
        Connection conec = funcionesBBDD.conectar();
         try{
            PreparedStatement ps= conec.prepareStatement(sqlMostrarContenido);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                txtNombre.setText(rs.getString("Nombre"));
                txtDirector.setText(rs.getString("Director"));
                txtDescripcion.setText(rs.getString("Descripcion"));
                txtDuracion.setText(rs.getString("Duracion"));
            }else{
                txtNombre.setText("");
                txtDirector.setText("");
                txtDescripcion.setText("");
                txtDuracion.setText("");
            }

      }catch(SQLException e){
          System.out.println("No se ha podido realizar la sentencia");
      }
      /* mostrarContenido(sqlMostrarContenido);
        txtNombre=datos[0];
        txtDescripcion=datos[1];
        txtDirector=datos[2];
        txtDuracion=datos[3];*/
    } 
    /*
       public Contenido visualizarContenido(String imagen){
           Contenido cont;
           Connection conec= funcionesBBDD.conectar();
           try{
           Query ps=conec.createQuery("Select Nombre, Descripcion,Director,Duracion from contenido where Imagen= :Imagen");
           Query ps.setParameter("Imagen", imagen);
           cont= (Contenido)  ps.ge
           }catch(SQLException e){
               System.out.println("Problemas en la consulta");
           }
           return cont;
       }*/
 /*   public void mostrarContenido(String sql){
        Connection conec= funcionesBBDD.conectar();
            try {
                PreparedStatement st = conec.prepareStatement(sql);
                ResultSet rs=st.executeQuery();
                Object[] datos =new Object[5];
                while(rs.next()){
                   datos[0]= rs.getString("Nombre");
                   datos[1]= rs.getString("Descripcion");
                   datos[2]= rs.getString("Director");
                   datos[3]= rs.getString("Duracion");
               }

                conec.close();
            } catch (SQLException ex) {
                System.out.println("No se ha podido recoger los datos");
            }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgContenido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JLabel();
        txtDirector = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgContenido.setText("imagen");

        txtNombre.setText("nombreSerie|pelicula");

        txtDuracion.setText("Duracion");

        txtDirector.setText("Director");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(36, 36, 36)
                        .addComponent(txtDirector)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtDuracion)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarContenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgContenido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JLabel txtDirector;
    private javax.swing.JLabel txtDuracion;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
