package JFrames;

import javax.swing.ImageIcon;
import JFrames.PortadaJFrame;
import funciones.funcionesBBDD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Carmen
 */
public class MostrarContenido extends javax.swing.JFrame {
    PortadaJFrame titulo = new PortadaJFrame();
    /**
     * Creates new form MostrarContenido
     */
    public MostrarContenido(){
        initComponents();
        txtNombre.setText("");
        txtDirector.setText("");
        txtDescripcion.setText("");
        txtDuracion.setText("");
        imgContenido.setIcon(new ImageIcon(""));
        this.setTitle("Mostrar Contenido");
        this.setLocationRelativeTo(null);
        String sqlMostrarContenido ="Select Nombre, Descripcion,Director,Duracion,Imagen from contenido where Nombre='El juego del calamar'"/*+titulo.texto+"'"*/;
        Connection conec = funcionesBBDD.conectar();
         try{
            PreparedStatement ps= conec.prepareStatement(sqlMostrarContenido);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                txtNombre.setText(rs.getString("Nombre"));
                txtDirector.setText(rs.getString("Director"));
                txtDescripcion.setText(rs.getString("Descripcion"));
                txtDuracion.setText(rs.getString("Duracion"));
                imgContenido.setIcon(new ImageIcon(rs.getString("Imagen")));
            }else{
                txtNombre.setText("");
                txtDirector.setText("");
                txtDescripcion.setText("");
                txtDuracion.setText("");
                imgContenido.setIcon(new ImageIcon(""));
            }
        conec.close();

      }catch(SQLException e){
          System.out.println("No se ha podido realizar la sentencia");
      }
         

             
         
      /* mostrarContenido(sqlMostrarContenido);
        txtNombre=datos[0];
        txtDescripcion=datos[1];
        txtDirector=datos[2];
        txtDuracion=datos[3];*/
    } 
    /*
       public Contenido visualizarContenido(String imagen){
           Contenido cont;
           Connection conec= funcionesBBDD.conectar();
           try{
           Query ps=conec.createQuery("Select Nombre, Descripcion,Director,Duracion from contenido where Imagen= :Imagen");
           Query ps.setParameter("Imagen", imagen);
           cont= (Contenido)  ps.ge
           }catch(SQLException e){
               System.out.println("Problemas en la consulta");
           }
           return cont;
       }*/
 /*   public void mostrarContenido(String sql){
        Connection conec= funcionesBBDD.conectar();
            try {
                PreparedStatement st = conec.prepareStatement(sql);
                ResultSet rs=st.executeQuery();
                Object[] datos =new Object[5];
                while(rs.next()){
                   datos[0]= rs.getString("Nombre");
                   datos[1]= rs.getString("Descripcion");
                   datos[2]= rs.getString("Director");
                   datos[3]= rs.getString("Duracion");
               }

                conec.close();
            } catch (SQLException ex) {
                System.out.println("No se ha podido recoger los datos");
            }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgContenido = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtNombre = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgContenido.setText("imagen");

        txtDuracion.setText("Duracion");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        txtNombre.setEditable(false);

        txtDirector.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtDuracion)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarContenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgContenido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JLabel txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
