package JFrames;
import Contenido.Contenido;
import java.sql.Connection;
import funciones.funcionesBBDD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Carmen
 */
public class PortadaJFrame extends javax.swing.JFrame {
        DefaultTableModel modelo;
        DefaultComboBoxModel ComboModelo;
        PreparedStatement st;
        String texto="";
        ArrayList listaTitulos;

    /**                                                           
     * Creates new form PrincipalJFrame
     */
    public PortadaJFrame() {                                                             
        initComponents();
        panelTabla.setVisible(false);
        Tabla.setVisible(false);
        visualizarContenido();
        this.setLocationRelativeTo(null);
        this.setTitle("Portada");
        listaTitulos=new ArrayList();
        String sql3Mejores="Select Nombre from contenido as c inner join usuariovaloracontenido on IdContenido=c.Id order by Puntuacion desc limit 3";
       ComboModelo= new DefaultComboBoxModel();
       llenarCB(sql3Mejores);
       //cargarDatosCombo(sql3Mejores);
        /* try {
             
                datosCombo(sql3Mejores);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PortadaJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        //Conectar base de datos
        Connection conec= funcionesBBDD.conectar();
        // Primera Consulta
        String sql1="Select Imagen from usuariovaloracontenido join contenido on idContenido=contenido.Id where Puntuacion=(Select max(Puntuacion) from usuariovaloracontenido)";
       try {
                PreparedStatement pst = conec.prepareStatement(sql1);
                ResultSet res = pst.executeQuery();
                if(res.next()){
                img1.setIcon(new ImageIcon(res.getString("Imagen"))); 

            }
        } catch (SQLException ex) {
            System.out.println("No se ha encontrado la imagen");
        }
        //Segunda Consulta
        String sql2=" Select Imagen from usuariovaloracontenido join contenido as c on idContenido=c.Id order by Puntuacion desc Limit 1,1";
        try {
                PreparedStatement ps2=conec.prepareStatement(sql2);
                ResultSet res2= ps2.executeQuery();
                if(res2.next()){
                img2.setIcon(new ImageIcon(res2.getString("Imagen")));
                }
        } catch (SQLException ex) {
            System.out.println("No se ha encontrado la imagen");
        }
         //Tercera Consulta
        String sql3=" Select Imagen from usuariovaloracontenido join contenido as c on idContenido=c.Id order by Puntuacion desc Limit 2,1";
        try {
                PreparedStatement ps3=conec.prepareStatement(sql3);
                ResultSet res3= ps3.executeQuery();
                if(res3.next()){
                img3.setIcon(new ImageIcon(res3.getString("Imagen")));
                }
                conec.close();
        } catch (SQLException ex) {
            System.out.println("No se ha encontrado la imagen");
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox<>();
        jVer = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        panelMostrarContenido = new javax.swing.JPanel();
        imgContenido = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtNombre = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        panelBuscar = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        rbSerie = new javax.swing.JRadioButton();
        rbPeli = new javax.swing.JRadioButton();
        bBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mPortada = new javax.swing.JMenu();
        mContenido = new javax.swing.JMenu();
        mSeries = new javax.swing.JMenuItem();
        mPeliculas = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mAcerca = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenu();
        mPerfil = new javax.swing.JMenuItem();
        mLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(877, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(828, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img1MouseClicked(evt);
            }
        });
        jPanel1.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 193, 224));
        jPanel1.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 193, 224));
        jPanel1.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 185, 224));

        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });
        jPanel1.add(jCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 160, -1));

        jVer.setText("Ver");
        jVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerActionPerformed(evt);
            }
        });
        jPanel1.add(jVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 80, -1));

        panelTabla.setPreferredSize(new java.awt.Dimension(828, 800));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        jPanel1.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, -1));

        panelMostrarContenido.setPreferredSize(new java.awt.Dimension(828, 500));

        imgContenido.setText("imagen");

        txtDuracion.setText("Duracion");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        txtNombre.setEditable(false);

        txtDirector.setEditable(false);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarContenidoLayout = new javax.swing.GroupLayout(panelMostrarContenido);
        panelMostrarContenido.setLayout(panelMostrarContenidoLayout);
        panelMostrarContenidoLayout.setHorizontalGroup(
            panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarContenidoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMostrarContenidoLayout.createSequentialGroup()
                        .addGroup(panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214))
                    .addGroup(panelMostrarContenidoLayout.createSequentialGroup()
                        .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        panelMostrarContenidoLayout.setVerticalGroup(
            panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarContenidoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMostrarContenidoLayout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtDuracion)
                .addGap(133, 133, 133))
        );

        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        buttonGroup1.add(rbSerie);
        rbSerie.setText("Series");

        buttonGroup1.add(rbPeli);
        rbPeli.setText("Películas");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addComponent(rbSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPeli)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mPortada.setText("Portada");
        jMenuBar1.add(mPortada);

        mContenido.setText("Contenido");

        mSeries.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mSeries.setText("Series");
        mSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSeriesActionPerformed(evt);
            }
        });
        mContenido.add(mSeries);

        mPeliculas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mPeliculas.setText("Peliculas");
        mPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPeliculasActionPerformed(evt);
            }
        });
        mContenido.add(mPeliculas);

        jMenuBar1.add(mContenido);

        mAyuda.setText("Ayuda");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/cerrar1.png"))); // NOI18N
        mSalir.setText("Salir de la aplicación");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mAyuda.add(mSalir);

        mAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/ayuda1.png"))); // NOI18N
        mAcerca.setText("Acerca de...");
        mAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaActionPerformed(evt);
            }
        });
        mAyuda.add(mAcerca);

        jMenuBar1.add(mAyuda);

        mUsuario.setText("Usuario");

        mPerfil.setText("Perfil");
        mPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPerfilActionPerformed(evt);
            }
        });
        mUsuario.add(mPerfil);

        mLogout.setText("Log Out");
        mUsuario.add(mLogout);

        jMenuBar1.add(mUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMostrarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(645, 645, 645))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMostrarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Evento que al pulsar Salga de la aplicación
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        //Salir de la aplicación
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPerfilActionPerformed
        //Mostrar el FRAME del PERFIL del USUARIO
        PerfilJFrame perfil = new PerfilJFrame();
        //Mostrar el frame de perfil
        perfil.setVisible(true);
        //ocultar este frame
        this.setVisible(false);
    }//GEN-LAST:event_mPerfilActionPerformed

    private void mAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaActionPerformed
        // TODO add your handling code here:
        AcercaDe acerca = new AcercaDe(this,rootPaneCheckingEnabled);
        acerca.setVisible(true);
        
    }//GEN-LAST:event_mAcercaActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
       visualizarTabla();

        // Búsqueda de contenido
        //Obtener texto a buscar
        String texto=txtBuscar.getText();
        if(texto.equals("")){
            JOptionPane.showMessageDialog(null,"No has puesto nada a buscar");
        } else if(rbSerie.isSelected()){
            String sqlBuscarSerie="Select Nombre, Imagen from contenido where Tipo='Series' and Nombre like '%"+ texto +"%'"; 
            crearTabla(sqlBuscarSerie);
            llenarCB(sqlBuscarSerie);
        }else if (rbPeli.isSelected()){
            String sqlBuscarPeli="Select Nombre, Imagen from contenido where Tipo='Peliculas' and Nombre like '%"+ texto +"%'"; 
            crearTabla(sqlBuscarPeli);
            cargarDatosCombo(sqlBuscarPeli);

        }else{
            JOptionPane.showMessageDialog(null, "Debe selecionar una opción");
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void mSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSeriesActionPerformed
        this.setTitle("Todas las Series");
        visualizarTabla();
        String sqlTSeries="Select Nombre from contenido where Tipo='Series'";
        crearTabla(sqlTSeries);
        cargarDatosCombo(sqlTSeries);
        
    }//GEN-LAST:event_mSeriesActionPerformed

    private void mPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPeliculasActionPerformed
        this.setTitle("Todas las Películas");
        visualizarTabla();
        String sqlTPelis="Select Nombre from contenido where Tipo='Peliculas'";
        crearTabla(sqlTPelis);
        cargarDatosCombo(sqlTPelis);     
    }//GEN-LAST:event_mPeliculasActionPerformed

    private void img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MouseClicked
      
    }//GEN-LAST:event_img1MouseClicked

    private void jVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerActionPerformed
       //texto=jCombo.getSelectedItem().toString();
       jPanel1.setVisible(false);
       panelBuscar.setVisible(false);
       System.out.println(texto);
       panelMostrarContenido.setVisible(true);
       System.out.println(texto);
        String sqlMostrarContenido ="Select Nombre, Descripcion,Director,Duracion,Imagen from contenido where Nombre='"+texto+"'";
        Connection conec = funcionesBBDD.conectar();
         try{
            PreparedStatement ps= conec.prepareStatement(sqlMostrarContenido);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                txtNombre.setText(rs.getString("Nombre"));
                txtDirector.setText(rs.getString("Director"));
                txtDescripcion.setText(rs.getString("Descripcion"));
                txtDuracion.setText(rs.getString("Duracion"));
                imgContenido.setIcon(new ImageIcon(rs.getString("Imagen")));
            }else{
                txtNombre.setText("");
                txtDirector.setText("");
                txtDescripcion.setText("");
                txtDuracion.setText("");
                imgContenido.setIcon(new ImageIcon(""));
            }
        conec.close();

      }catch(SQLException e){
          System.out.println("No se ha podido realizar la sentencia");
      }
    }//GEN-LAST:event_jVerActionPerformed

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
        // TODO add your handling code here:
        texto=jCombo.getSelectedItem().toString();

    }//GEN-LAST:event_jComboActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        PortadaJFrame portada =new PortadaJFrame();
        portada.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed
     public void visualizarTabla(){
        //Ocultar elemenos
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        //Hacer visible la tabla
        panelTabla.setVisible(true);
        Tabla.setVisible(true);
        Tabla.removeAll();
    }
    public void crearTabla(String sql){
         Connection conec= funcionesBBDD.conectar();
            try {
                st= conec.prepareStatement(sql);
                ResultSet rs=st.executeQuery();
                Object[] nombre =new Object[1];
                modelo = (DefaultTableModel) Tabla.getModel();
                //Vaciar la tabla antes de cada búsqueda
                modelo.setRowCount(0);
                while(rs.next()){
                   nombre[0]= rs.getString("Nombre");
                   modelo.addRow(nombre);
               }
                Tabla.setModel(modelo);
                conec.close();
            } catch (SQLException ex) {
                System.out.println("No se ha podido añadir la tabla");
            }
    }
    public void cargarDatosCombo(String sql){
        Connection conec=funcionesBBDD.conectar();
        try{
            jCombo.removeAllItems();
            PreparedStatement ps=conec.prepareStatement(sql);
            ResultSet rs= ps.executeQuery(sql);
            while(rs.next()){
                jCombo.addItem(rs.getString("Nombre"));
            }
            conec.close();
        }catch(SQLException e){
            System.out.println("No se ha podido cargar el combo");
        }
    }
    public void llenarCB(String sql){
         Connection conec=funcionesBBDD.conectar();
        try{
            ComboModelo.removeAllElements();
            PreparedStatement ps=conec.prepareStatement(sql);
            ResultSet rs= ps.executeQuery(sql);
            while(rs.next()){
                ComboModelo.addElement(rs.getString("Nombre"));
            }
            jCombo.setModel(ComboModelo);
            conec.close();
        }catch(SQLException e){
            System.out.println("No se ha podido cargar el combo");
        }
    }
    
    public void datosCombo(String sql) throws ClassNotFoundException{
           jCombo.removeAllItems();
            listaTitulos=funcionesBBDD.getTitulo(sql);
            Iterator itListaTitulos=listaTitulos.iterator();
            while(itListaTitulos.hasNext()){
            Contenido nContenido=(Contenido) itListaTitulos.next();
            jCombo.addItem(nContenido.toString());
            }
    }
    
    public void visualizarContenido(){
        panelMostrarContenido.setVisible(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortadaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortadaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortadaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortadaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortadaJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton btnAtras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel imgContenido;
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jVer;
    private javax.swing.JMenuItem mAcerca;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mContenido;
    private javax.swing.JMenuItem mLogout;
    private javax.swing.JMenuItem mPeliculas;
    private javax.swing.JMenuItem mPerfil;
    private javax.swing.JMenu mPortada;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mSeries;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelMostrarContenido;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JRadioButton rbPeli;
    private javax.swing.JRadioButton rbSerie;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JLabel txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
